#!/bin/bash
set -e
set -x

# requirements
#   brew install molecule flake8 shellcheck ansible-lint yamllint
#   pip3 install pytest molecule-docker pytest-testinfra

# Pre-commit hooks to copy steps from default CI/CD pipeline. See `bitbucket-pipelines.yml` for details.
[ $(command -v shellcheck) ] && find . -path ./tmp -prune -false -o -name "*.sh" -print -exec shellcheck -x {} \;
[ $(command -v ansible-lint) ] && ansible-lint --nocolor -p --parseable-severity
[ $(command -v yamllint) ] && yamllint -s  .
[ $(command -v flake8) ] && flake8

# the following takes a while to complete, consider running it manually
#   molecule test
