---
- name: Include Debian tasks
  include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include Generic tasks
  include_tasks: install-Generic.yml
  when: ansible_os_family != 'Debian'
